repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-merge-conflict
      - id: check-added-large-files

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.0
    hooks:
      - id: ruff-check
        name: 'backend: ruff check (lint, autofix)'
        args: [--fix]
        files: ^backend/.*\.py$
      - id: ruff-format
        name: 'backend: ruff format'
        files: ^backend/.*\.py$

  - repo: local
    hooks:
      - id: frontend-prettier
        name: 'frontend: prettier'
        language: system
        entry: npm --prefix frontend run prettier
        pass_filenames: false
        files: ^frontend/.*\.(ts|tsx|js|jsx|html|css|scss|md|json|yml|yaml)$

      - id: frontend-lint
        name: 'frontend: ng lint'
        language: system
        entry: npm --prefix frontend run lint
        pass_filenames: false
        files: ^frontend/.*\.(ts|tsx|js|jsx|html)$
